name: Deploy - Google Cloud Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Google Cloud Functions
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project $GCP_PROJECT_ID
          gcloud functions deploy YOUR_FUNCTION_NAME --entry-point YOUR_FUNCTION_ENTRYPOINT --runtime nodejs14 --trigger-http --allow-unauthenticated
        if: github.ref == 'refs/heads/main'
