name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Setup GCP Credentials
        env:
          SA_KEY: ${{ secrets.SA_KEY }}
        run: |
          echo "$SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable Cloud Functions API
        run: gcloud services enable cloudfunctions.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Platform
        run: |
          gcloud functions deploy tech-challenge --trigger-http --runtime nodejs14 --entry-point app --allow-unauthenticated
