name: Deploy API Gateway - Cloud Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Instalar dependencias
        run: npm install

      - name: Configurar GCP Credentials
        env:
          SA_KEY: ${{ secrets.SA_KEY }}
        run: |
          echo "$SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Habilitar Cloud Functions
        run: gcloud services enable cloudfunctions.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy
        run: |
          gcloud functions deploy tech-challenge --trigger-http --runtime nodejs14 --entry-point app --allow-unauthenticated
