name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Setup GCP Credentials
        env:
          SA_KEY: ${{ secrets.SA_KEY }}
        run: |
          echo "$SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project your-gcp-project-id

      # Deploy to GCP
      - name: Deploy to Google Cloud Platform
        run: |
          # Your deployment commands go here
          # For example, deploying to Cloud Functions:
          # gcloud functions deploy your-function-name --trigger-http --runtime nodejs14 --entry-point yourEntryPoint
