name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Setup GCP Credentials
        run: |
          echo "${{ secrets.SA_KEY }}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}  # Substitua pelo seu Project ID

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy tech-challenge --trigger-http --runtime nodejs14 --entry-point yourEntryPoint
      - name: Retrieve function URL
        run: |
          FUNCTION_URL=$(gcloud functions describe your-function-name --format 'value(httpsTrigger.url)')
          echo "Function URL: $FUNCTION_URL"
          echo "FUNCTION_URL=$FUNCTION_URL" >> $GITHUB_ENV

      - name: Output function URL
        run: echo "Deployed to ${{ env.FUNCTION_URL }}"
