name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Setup GCP Credentials
        env:
          SA_KEY: ${{ secrets.SA_KEY }}
        run: |
          echo "$SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project your-gcp-project-id  # Substitua pelo ID real do seu projeto GCP

      # Aqui vamos supor que você está implantando uma função HTTP Cloud Function.
      - name: Deploy to Google Cloud Platform
        run: |
          gcloud functions deploy your-function-name --trigger-http --runtime nodejs14 --entry-point yourEntryPoint --allow-unauthenticated
          # Substitua 'your-function-name' pelo nome da sua função Cloud Function.
          # Substitua 'yourEntryPoint' pelo nome do entry point da sua função, por exemplo, o nome da função exportada no seu arquivo index.js.
